#!/usr/bin/env bash
#
# gaming.sh — Install gaming stack untuk MangoWM / Fedora setup
# Jalankan setelah masuk desktop dan install.sh selesai
#
# Usage:
#   chmod +x gaming.sh
#   ./gaming.sh
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="${SCRIPT_DIR}/gaming.log"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${CYAN}[INFO]${NC}  $*"; }
log_ok()   { echo -e "${GREEN}[OK]${NC}   $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_err()  { echo -e "${RED}[ERROR]${NC} $*"; }

exec > >(tee -a "$LOG_FILE") 2>&1
log_info "Logging to: ${LOG_FILE}"
trap 'log_err "Failed at line ${LINENO}: ${BASH_COMMAND}"' ERR

# ---------------------------------------------------
install_gaming_packages() {
    log_info "Installing gaming packages..."

    # Check multilib - Wajib untuk wine dan 32-bit
    if ! grep -Eq "^\[multilib\]|^include=multilib" /etc/yum.repos.d/fedora.repo 2>/dev/null; then
        log_warn "Multilib not enabled - enabling now..."
        sudo sed -i '/^\[fedora\]/,/^\[/ s/^enabled=1/enabled=1\ninclude=multilib/' /etc/yum.repos.d/fedora.repo 2>/dev/null || true
    fi

    sudo dnf install -y \
        gamemode gamemode-devel \
        gamescope \
        mangohud \
        wine winetricks \
        vkbasalt || {
        log_warn "Some packages failed - retrying with --skip-unavailable..."
        sudo dnf install -y --skip-unavailable \
            gamemode gamemode-devel \
            gamescope \
            mangohud \
            wine winetricks \
            vkbasalt || true
    }

    # goverlay - optional (deprecated, mangohud sudah include)
    log_info "Installing goverlay (optional)..."
    sudo dnf install -y goverlay 2>/dev/null || log_warn "goverlay unavailable - skip"

    # 32-bit mesa — untuk game lama yang butuh lib32
    sudo dnf install -y \
        mesa-dri-drivers.i686 \
        mesa-vulkan-drivers.i686 || true

    log_ok "Gaming packages installed."
}

# ---------------------------------------------------
install_steam() {
    log_info "Steam - skip (manual install)"
    log_info "Manual: sudo dnf install steam"
    log_info "  Or from: https://store.steampowered.com/about/"
    log_info "  NVIDIA launch options: prime-run %command%"
}

# ---------------------------------------------------
install_discord() {
    log_info "Discord - skip (manual install from flathub later)"
    log_info "Manual: flatpak install flathub com.discord.Discord"
}

# ---------------------------------------------------
install_mangohud_config() {
    local cfg_dir="${HOME}/.config/MangoHud"
    local cfg_file="${cfg_dir}/MangoHud.conf"

    if [[ -f "$cfg_file" ]]; then
        log_ok "MangoHud config already exists. Skipping."
        return 0
    fi

    log_info "Creating MangoHud default config..."
    mkdir -p "$cfg_dir"

    cat > "$cfg_file" << 'MANGOEOF'
# MangoHud config — generated by gaming.sh
# Dokumentasi: https://github.com/flightlessmango/MangoHud

legacy_layout=false
horizontal
gpu_stats
gpu_temp
cpu_stats
cpu_temp
ram
fps
frametime=0
hud_no_margin
table_columns=3
font_size=24
MANGOEOF

    log_ok "MangoHud config created at ${cfg_file}"
}

# ---------------------------------------------------
configure_gamemode() {
    if ! rpm -q gamemode &>/dev/null; then
        log_warn "gamemode tidak terinstall, skip config."
        return 0
    fi

    # Tambah user ke group gamemode
    if ! groups "$USER" | grep -q gamemode; then
        sudo usermod -aG gamemode "$(whoami)"
        log_ok "User ${USER} ditambahkan ke group gamemode."
        log_warn "Logout/login agar group aktif."
    else
        log_ok "User sudah di group gamemode."
    fi

    systemctl --user enable --now gamemoded 2>/dev/null || log_warn "User service sudah jalan atau gagal"
    log_ok "gamemode configured."
    log_info "  Aktifkan di game: gamemoderun <app>"
    log_info "  Steam: gamemoderun %command%"
    log_info "  Kombinasi NVIDIA: prime-run gamemoderun %command%"
}

# ---------------------------------------------------
preflight_checks() {
    log_info "Running preflight checks..."

    if [[ "$(id -u)" -eq 0 ]]; then
        log_err "Jangan jalankan sebagai root."
        exit 1
    fi

    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        local supported_fedora=false
        case "${ID:-}" in
            fedora|fedora-linux) supported_fedora=true ;;
        esac
        if [[ "$supported_fedora" == "false" ]]; then
            log_err "This script is designed for Fedora. Detected: ${ID:-unknown}"
            exit 1
        fi
        log_ok "Detected ${ID} ${VERSION_ID:-unknown}"
    else
        log_err "Cannot detect operating system."
        exit 1
    fi

    log_ok "Preflight checks passed."
}

# ---------------------------------------------------
main() {
    preflight_checks
    install_gaming_packages
    install_steam
    install_discord
    install_mangohud_config
    configure_gamemode

    echo ""
    log_ok "========================================"
    log_ok " Gaming setup complete!"
    log_ok "========================================"
    echo ""
    log_info "Log: ${LOG_FILE}"
    echo ""
    log_info "Manual installs (Flatpak):"
    log_info "  ProtonPlus: flatpak install flathub com.vysp3r.ProtonPlus"
    log_info "  Discord:    flatpak install flathub com.discord.Discord"
    echo ""
    log_info "Steam launch options untuk NVIDIA + gamemode:"
    log_info "  prime-run gamemoderun %command%"
    echo ""
    log_info "MangoHud overlay:"
    log_info "  MANGOHUD=1 prime-run %command%"
    echo ""
}

main "$@"
