# Niri: prefer client-side decorations + native wayland for all toolkits
GTK_CSD=1
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=gtk3
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
XDG_CURRENT_DESKTOP=niri
XDG_SESSION_TYPE=wayland
