color0 #0b0e14
color1 #d95757
color2 #e6b450
color3 #8e959e
color4 #39bae6
color5 #aad94c
color6 #39bae6
color7 #d1d1c7
color8 #1e222a
color9 #d95757
color10 #e6b450
color11 #8e959e
color12 #39bae6
color13 #aad94c
color14 #39bae6
color15 #d1d1c7

cursor                #d1d1c7
cursor_text_color     #0b0e14
background            #0b0e14
foreground            #d1d1c7
selection_foreground  #d1d1c7
selection_background  #565b66
active_border_color   #e6b450
inactive_border_color #565b66
url_color             #e6b450

active_tab_foreground   #0b0e14
active_tab_background   #e6b450
inactive_tab_foreground #8e959e
inactive_tab_background #565b66
cursor_trail_color      #8e959e
