config_version = 12

[audio]
enable_overdrive = true
enable_sounds = true
notification_sound = "/home/mindset/.local/state/noctalia/sounds/apple-pay-original.wav"
sound_volume = 0.99999997764825821
volume_change_sound = "/home/mindset/.local/state/noctalia/sounds/volume-change.wav"

[bar]
order = [ "Mindset" ]

    [bar.Mindset]
    background_opacity = 0.4999999888241291
    center = [ "workspaces", "audio_visualizer", "media" ]
    contact_shadow = true
    end = [
        "tray",
        "notifications",
        "clipboard",
        "todo",
        "notes",
        "gamermode",
        "widget",
        "bluetooth",
        "toggle_2",
        "network",
        "volume",
        "battery",
        "control-center"
    ]
    font_family = "Comic Sans MS"
    font_weight = 400
    margin_ends = 25
    radius = 50
    start = [ "launcher", "clock", "cpu", "temp", "ram", "privacy" ]
    thickness = 30

[battery]
warning_threshold = 20

[brightness]
enable_ddcutil = true
minimum_brightness = 0.099999997764825821

[calendar]
enabled = true
refresh_minutes = 5

    [calendar.account.personal]
    color = "error"
    name = "Shiin"
    type = "google"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "dark_mode"

[[control_center.shortcuts]]
type = "power_profile"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 3

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 1620

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 1800

[location]
auto_locate = true
latitude = -6.9088900000000004
longitude = 108.48972000000001
sunrise = "06:00"
sunset = "18:00"

[lockscreen]
blur_intensity = 0.0

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005"
]

    [lockscreen_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 201.0
    box_width = 720.0
    cx = 960.0
    cy = 879.5
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "on_primary"
        background_opacity = 0.59999999999999998
        background_radius = 20.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 12.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_session_buttons = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 224.0
    box_width = 448.0
    cx = 960.0
    cy = 148.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        background_opacity = 0.52000000000000002
        center_text = true
        clock_style = "digital"
        font_family = ""
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 170.0
    cy = 910.0
    output = "eDP-1"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10.0
        background_radius = 12.0
        bar_width = 0.59999999999999998
        bloom_intensity = 0.5
        fade_when_idle = true
        inner_diameter = 0.69999999999999996
        primary_color = "primary"
        ring_opacity = 0.80000000000000004
        rotation_speed = 2.0
        secondary_color = "secondary"
        sensitivity = 2.0
        visualization_mode = "all"
        wave_thickness = 1.0

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 208.0
    box_width = 304.0
    cx = 976.0
    cy = 340.0
    output = "eDP-1"
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10.0
        background_radius = 12.0
        color = "on_surface"
        font_family = ""
        forecast_days = 3
        shadow = true
        show_forecast = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 80.0
    box_width = 872.0
    cx = 960.0
    cy = 1020.0
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false
        bands = 60.0
        centered = true
        color_2 = "secondary"
        mirrored = true
        show_when_idle = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 0.0
    box_width = 0.0
    cx = 1744.0
    cy = 910.0
    output = "eDP-1"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10.0
        background_radius = 12.0
        bar_width = 0.59999999999999998
        bloom_intensity = 0.5
        fade_when_idle = true
        inner_diameter = 0.69999999999999996
        primary_color = "primary"
        ring_opacity = 0.80000000000000004
        rotation_speed = 2.0
        secondary_color = "secondary"
        sensitivity = 2.0
        visualization_mode = "all"
        wave_thickness = 1.0

[notification]
background_opacity = 0.4999999888241291
layer = "overlay"
scale = 0.7500000037252903

[osd]
background_opacity = 0.4999999888241291
offset_y = 20
position = "bottom_center"
scale = 0.80000000447034836

[plugin_settings."alexander/screen-toolkit"]
gif-max-seconds = 60
panel-full_open_near_click = true
panel-full_position = "auto"
panel-legacy_open_near_click = true
panel-legacy_position = "auto"
panel-mode = "legacy"
panel_open_near_click = true
panel_position = "auto"
record-audio-in = true
record-audio-out = true
record-codec = "hevc"
record-fps = 144
result_open_near_click = true
result_position = "auto"

[plugin_settings."blackbartblues/audio-switcher"]
audio-switcher_placement = "floating"
audio-switcher_position = "auto"

[plugin_settings."blackbartblues/keymap"]
columns = 4

[plugin_settings."cleboost/hotspot"]
panel_placement = "floating"
panel_position = "auto"
password = "43211234"
ssid = "Linux_User"

[plugin_settings."cleboost/jetbrains-provider"]
max_results = 30

[plugin_settings."cleboost/zed-provider"]
max_results = 30

[plugin_settings."gustav0ar/drive-health"]
critical_temperature = 90
drives_position = "auto"
life_warning_percent = 25
system_collector_enabled = true
warning_temperature = 80

[plugin_settings."h465855hgg/lyrics"]
max_chars = 40
player_allowlist = []

[plugin_settings."mindset/gamer-mode"]
main_open_near_click = true
main_placement = "floating"

[plugin_settings."mindset/hotspot"]
panel_placement = "floating"
panel_position = "auto"

[plugin_settings."mindset/hypr-animations"]
panel_open_near_click = true

[plugin_settings."mindset/keybind-cheatsheet"]
cheatsheet_position = "auto"
compositor = "hyprland"
hyprland_parser = "lua"

[plugin_settings."nightwatch75/todo"]
panel_placement = "floating"

[plugin_settings."noctalia/mpvpaper"]
picker_open_near_click = true
picker_placement = "floating"
video_directory = "/home/mindset/Videos/Wallpaper"

[plugin_settings."noctalia/screen_recorder"]
audio_codec = "aac"
color_range = "full"
quality = "ultra"
video_source = "focused"

[plugin_settings."noctalia/wallhaven"]
browser_open_near_click = true
browser_placement = "floating"

[plugin_settings."oldirtty/color_picker"]
panel_position = "top_center"

[plugins]
enabled = [
    "noctalia/translator",
    "noctalia/notes",
    "noctalia/wallhaven",
    "noctalia/kaomoji",
    "noctalia/mpvpaper",
    "nightwatch75/todo",
    "nightwatch75/file-search",
    "dunarand/tmux-provider",
    "cleboost/ssh-launcher",
    "weinguyen/shell-command",
    "alexander/screen-toolkit",
    "mindset/hotspot",
    "mindset/hypr-layouts",
    "mindset/hypr-animations",
    "mindset/hypr-decorations",
    "mindset/hypr-windows",
    "mindset/gamer-mode",
    "cleboost/jetbrains-provider",
    "cleboost/zed-provider",
    "mindset/keybind-cheatsheet"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/tofan79/mindset-noctalia-plugins"
    name = "mindset"

[shell]
app_icon_color = "error"
avatar_path = "/home/mindset/.local/state/noctalia/avatar/images.jpeg"
clipboard_image_action_command = "satty -f -"
corner_radius_scale = 1.2500000186264515
external_ip_enabled = true
font_family = "Comic Sans MS"
niri_overview_type_to_launch_enabled = true
panel_anchor_bar = "Mindset"
password_style = "random"
polkit_agent = true
screen_time_enabled = true
settings_show_advanced = true
settings_window_translucent = true

    [shell.launcher]
    session_search = true
    sort_by_usage = false

    [shell.panel]
    clipboard_position = "auto"
    control_center_placement = "floating"
    floating_layer = "top"
    launcher_position = "auto"
    launcher_sort_by_usage = false
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    session_placement = "floating"
    transparency_mode = "glass"
    wallpaper_placement = "floating"

    [shell.screenshot]
    confirm_region = true

    [shell.session]
    grid_columns = 1

[system.monitor]
cpu_temp_activity_threshold = 80
cpu_temp_critical_threshold = 100
gpu_poll_seconds = 2
gpu_temp_activity_threshold = 80
gpu_temp_critical_threshold = 100
net_rx_activity_threshold = 5.0
net_tx_activity_threshold = 5.0
network_poll_seconds = 2
ram_pct_activity_threshold = 80
ram_pct_critical_threshold = 100
swap_pct_activity_threshold = 50
swap_pct_critical_threshold = 100

[theme]
builtin = "Ayu"
community_palette = "GitHub Dark"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "foot", "gtk3", "gtk4", "hyprland", "kcolorscheme", "qt" ]
    community_ids = [
        "opencode",
        "zen-browser",
        "telegram",
        "inkscape",
        "libreoffice",
        "neovim",
        "zed",
        "heroiclauncher",
        "steam",
        "fastfetch",
        "obs",
        "hyprtoolkit",
        "papirus-icons",
        "bat",
        "lazygit",
        "yazi"
    ]

[wallpaper]
fill_mode = "span"
transition_on_startup = true

    [wallpaper.automation]
    enabled = true
    interval_seconds = 600

    [wallpaper.default]
    path = "/home/mindset/Pictures/Wallpapers/BG03.png"

    [wallpaper.last]
    path = "/home/mindset/Pictures/Wallpapers/BG03.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/mindset/Pictures/Wallpapers/BG03.png"

[weather]
refresh_minutes = 5

[widget.audio_visualizer]
bands = 50
color_2 = "secondary"
show_when_idle = true
width = 100.0

[widget.clock]
capsule = true
capsule_opacity = 0.29999999999999999
capsule_padding = 15
capsule_radius = 12
format = "{:%H:%M:%S}"

[widget.cpu]
stat = "cpu_temp"

[widget.gamermode]
type = "mindset/gamer-mode:gamermode"

[widget.launcher]
glyph = "brand-apple-filled"

[widget.notes]
type = "noctalia/notes:notes"

[widget.privacy]
hide_inactive = true

[widget.spacer_2]
type = "spacer"

[widget.temp]
stat = "gpu_temp"

[widget.todo]
type = "nightwatch75/todo:todo"

[widget.toggle_2]
type = "mindset/hotspot:toggle"

[widget.widget]
type = "alexander/screen-toolkit:widget"