linux_display_server wayland
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0
disable_ligatures never
cursor_shape block
cursor_blink_interval 2
scrollback_lines 10000
repaint_delay 6
sync_to_monitor yes
confirm_os_window_close 0
hide_window_decorations yes
shell_integration enabled
enable_audio_bell no

window_padding_width  14
background_opacity  0.90

tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5

include dank-tabs.conf
include dank-theme.conf

map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter
map ctrl+home resize_window reset
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

enabled_layouts splits,stack

allow_remote_control yes
listen_on unix:/tmp/kitty

map ctrl+shift+enter launch --location=vsplit --cwd=current
map ctrl+shift+s save_as_session --use-foreground-process --relocatable
map ctrl+shift+a goto_session ~/.config/kitty/sessions
