linux_display_server wayland
font_family Fira Code Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10.0
disable_ligatures never
cursor_shape block
cursor_blink_interval 0
scrollback_lines 10000
repaint_delay 6
sync_to_monitor yes
confirm_os_window_close 0
hide_window_decorations yes
shell_integration no-cursor
enable_audio_bell no

#window
window_padding_width  14
background_opacity  0.90
# foreground            #e0e3de
# background            #101411
# selection_foreground  #1d3526
# selection_background  #b1ceb8

# Black
# color0   #101411
# color8   #808b84

# Red
# color1   #f6946e
# color9   #ffba9f

# Green
# color2   #6bd66c
# color10  #a5ffa7

# Yellow
# color3   #fff172
# color11  #fff6a5

# Blue
# color4   #7acb96
# color12  #a9ebc0

# Magenta
# color5   #26633c
# color13  #c3ffd8

# Cyan
# color6   #8fd6a8
# color14  #d8ffe6

# White
# color7   #d3e0d8
# color15  #f8fffa

# Cursor
# cursor #e0e3de
# cursor_text_color #bfc9bf

# The color for highlighting URLs on mouse-over
# url_color #8fd6a8

# Window borders
# active_border_color #8fd6a8
# inactive_border_color #101411
# bell_border_color #fff172

# Tab bar
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5
# tab_bar_margin_color    #101411
# tab_bar_background      #101411
# active_tab_foreground   #00391f
# active_tab_background   #8fd6a8
active_tab_font_style   bold
# inactive_tab_foreground #bfc9bf
# inactive_tab_background #101411
inactive_tab_font_style normal
tab_activity_symbol     " ● "
tab_title_template      "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"

# Title bar
# macos_titlebar_color #101411

# Resizing windows
map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter
map ctrl+home resize_window reset

# Enable splits layout
enabled_layouts splits,stack

# Allow felix to open files in new panes
allow_remote_control yes
listen_on unix:/tmp/kitty

# Shell
shell zsh

# Open new panes side-by-side (vertical split line)
map ctrl+shift+enter launch --location=vsplit --cwd=current

# Session management
map ctrl+shift+s save_as_session --use-foreground-process --relocatable
map ctrl+shift+a goto_session ~/.config/kitty/sessions


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
