color_theme = "noctalia"
theme_background = True
truecolor = True
force_tty = False
preserve_aspect_ratio = True

# Base
shown_boxes = "proc cpu mem net"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_reversed = False
proc_gradient = True
proc_per_core = True
proc_tree = False
proc_colors = True
proc_display = "tree"  # tree, detailed, list
