# ============================================
# Mango WM Config — Main Entry
# ============================================
# More options: https://github.com/DreamMaoMao/mango/wiki/
# Reload with: SUPER + r

source=~/.config/mango/env.conf
source=~/.config/mango/settings.conf
source=~/.config/mango/monitor.conf
source=~/.config/mango/layouts.conf
source=~/.config/mango/rules.conf
source=~/.config/mango/keybinds.conf

exec-once=~/.config/mango/autostart.sh

# This sources the noctalia theme

source = /home/mindset/.config/mango/noctalia.conf

