# Mango WM — Main Entry (modular)
exec-once = /usr/libexec/xdg-desktop-portal &>/dev/null & /usr/libexec/xdg-desktop-portal-gtk &>/dev/null & /usr/libexec/xdg-desktop-portal-wlr &>/dev/null & dms run &

source=~/.config/mango/env.conf
source=~/.config/mango/monitor.conf
source=~/.config/mango/layouts.conf
source=~/.config/mango/settings.conf
source=~/.config/mango/keybinds.conf
source=~/.config/mango/rules.conf

source=~/.config/mango/dms/colors.conf
source=~/.config/mango/dms/layout.conf
source=~/.config/mango/dms/outputs.conf
