# Mango WM — Main Entry (modular)
exec-once = dms run &

source=~/.config/mango/env.conf
source=~/.config/mango/monitor.conf
source=~/.config/mango/layouts.conf
source=~/.config/mango/settings.conf
source=~/.config/mango/keybinds.conf
source=~/.config/mango/rules.conf

source=~/.config/mango/dms/colors.conf
source=~/.config/mango/dms/layout.conf
source=~/.config/mango/dms/outputs.conf
