# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x010409ff
rootcolor = 0x010409ff
bordercolor = 0x515c67ff
focuscolor = 0x58a6ffff
maximizescreencolor = 0xbc8cffff
urgentcolor = 0xf85149ff
scratchpadcolor = 0xbc8cffff
globalcolor = 0x004da5ff
overlaycolor = 0x5a00d9ff
