# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131318ff
bordercolor = 0x918f9cff
focuscolor = 0xbfc2ffff
maximizescreencolor = 0xc3c4e7ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xfcadebff
globalcolor = 0x3a3f87ff
overlaycolor = 0x434462ff
