# Window & Layer Rules

# Floating apps
windowrule = isfloating:1, width:1200, height:800, appid:[Ss]team
windowrule = isfloating:1, width:800, height:600, title:LocalSend
windowrule = isfloating:1, width:800, height:600, appid:localsend
windowrule = isfloating:1, width:800, height:600, appid:org.localsend.localsend
windowrule = isfloating:1, width:400, height:500, appid:org.gnome.Calculator
windowrule = isfloating:1, width:800, height:600, appid:org.pulseaudio.pavucontrol
windowrule = isfloating:1, width:800, height:600, appid:pavucontrol
windowrule = isfloating:1, width:1200, height:700, title:btop
windowrule = isfloating:1, width:900, height:700, appid:imv
windowrule = isfloating:1, width:900, height:600, appid:mpv

# Idle inhibit untuk Steam (cegah lock pas main game)
windowrule = idleinhibit_when_focus:1, appid:[Ss]team

# Animasi & blur off buat layer DMS (selection overlay)
layerrule = noanim:1, noblur:1, layer_name:selection
