# Window & Layer Rules

# Floating kitty — for yazi, floating terminal, etc.
windowrule=isfloating:1,width:900,height:600,title:floating-kitty
# Launch with: kitty -T floating-kitty

# Steam — idle inhibit agar gak lock screen pas main game
windowrule=indleinhibit_when_focus:1,appid:steam
